version: '3.8'
services:
  django:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY:-insecure-7j(@z8g0qc0hsl3wiqp55_ult3k3g&lh17@643@*g_q=sikrxr}
        PYTHONUNBUFFERED: ${PYTHONUNBUFFERED:-0}
        ADMIN_USERNAME: ${ADMIN_USERNAME}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        DEBUG: ${DEBUG:-false}
        ALLOWED_HOSTS: ${ALLOWED_HOSTS:-0.0.0.0}
        CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-http://0.0.0.0:80}
        LOAD_SAMPLE_DATA: ${LOAD_SAMPLE_DATA:-false}
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8025
    env_file:
      - .env
    command: /app/start.sh

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/data/staticfiles
      - media_volume:/data/media
    ports:
      - "${PUBLIC_PORT:-80}:80"
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
