FROM nginx:latest

# Entfernen Sie die Standardkonfiguration von Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Fügen Sie Ihre benutzerdefinierte Konfigurationsdatei hinzu
COPY nginx.conf /etc/nginx/conf.d
